# Generated by Django 5.2.8 on 2025-11-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('halaman', models.IntegerField(blank=True, null=True, verbose_name='Halaman')),
                ('posisi_teks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posisi/Line')),
                ('tanggal_komentar', models.DateTimeField(auto_now_add=True)),
                ('laporan_versi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar_laporan', to='documents.laporanversi')),
            ],
            options={
                'ordering': ['tanggal_komentar'],
            },
        ),
    ]
