# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanVersi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_versi', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='laporan_ta/%Y/%m/%d/', verbose_name='File Laporan')),
                ('catatan_revisi', models.TextField(blank=True, null=True, verbose_name='Catatan Mahasiswa')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
