# Generated by Django 5.2.8 on 2025-11-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('ta_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanversi',
            name='tugas_akhir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_laporan', to='ta_management.tugasakhir', verbose_name='Proyek Tugas Akhir'),
        ),
        migrations.AlterUniqueTogether(
            name='laporanversi',
            unique_together={('tugas_akhir', 'nomor_versi')},
        ),
    ]
