# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TugasAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('status_bimbingan', models.CharField(choices=[('PROP', 'Draft Proposal'), ('BIMB', 'Sedang Bimbingan'), ('REVI', 'Perlu Revisi'), ('SIDANG', 'Siap Sidang'), ('LULUS', 'Selesai/Lulus')], default='PROP', max_length=10, verbose_name='Status Proyek')),
                ('tanggal_mulai', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tugas Akhir',
                'verbose_name_plural': 'Daftar Tugas Akhir',
            },
        ),
    ]
