# Generated by Django 5.2.8 on 2025-11-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ta_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugasakhir',
            name='dosen_pembimbing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_ta', to='users.dosenprofile', verbose_name='Dosen Pembimbing'),
        ),
        migrations.AddField(
            model_name='tugasakhir',
            name='mahasiswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyek_ta', to='users.mahasiswaprofile', verbose_name='Mahasiswa'),
        ),
    ]
